
version: '3'
services:
  fastify:
    build:
      context: ./Back/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/TaskHubDB

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
